//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceStalkerScrape.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int CustomerId { get; set; }
        public string Address { get; set; }
        public int Qty { get; set; }
        public double TotalPrice { get; set; }
        public int Rating { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual tblProducts tblProducts { get; set; }
    }
}
