//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceStalkerScrape.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProducts
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public double Price { get; set; }
        public Nullable<double> Rating { get; set; }
        public string Description { get; set; }
        public string Link { get; set; }
    
        public virtual PriceHistory PriceHistory { get; set; }
    }
}
